export const LENGTH = 'LENGTH' ;
export const TEMPRATURE = 'TEMPRATURE' ;
export const VOLUME = 'VOLUME' ;

export const FIRSTFUNCTION = 'FIRSTFUNCTION' ;
export const SECONDFUNCTION = 'SECONDFUNCTION' ;

export const LENGTHTOGGLE = 'LENGTHTOGGLE' ;
export const VOLUMETOGGLE = 'VOLUMETOGGLE' ;
export const TEMPERATURETOGGLE = 'TEMPERATURETOGGLE' ;
export const LENGTHTOGGLEOFF = 'LENGTHTOGGLEOFF' ;
export const VOLUMETOGGLEOFF = 'VOLUMETOGGLEOFF' ;
export const TEMPERATURETOGGLEOFF = 'TEMPERATURETOGGLEOFF' ;

// export const LENGTHCOLOR = 'LENGTHCOLOR';
// export const TEMPRATURECOLOR = 'TEMPRATURECOLOR';
// export const VOLUMECOLOR = 'VOLUMECOLOR';



// LENGTHTOGGLE, VOLUMETOGGLE, TEMPERATURETOGGLE,LENGTHTOGGLEOFF, VOLUMETOGGLEOFF, TEMPERATURETOGGLEOFF 